# -*- coding: utf-8 -*-
"""inomatics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkamfqDnjXGi8nmMexRfqaUX39sqCMD4
"""

import pandas as pd

orders = pd.read_csv("orders.csv")
orders.head()

users = pd.read_json("users.json")
users.head()

import sqlite3

# Create in-memory database
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# Read and execute SQL file
with open("restaurants.sql", "r") as file:
    sql_script = file.read()

cursor.executescript(sql_script)

# Load restaurant table into pandas
restaurants = pd.read_sql("SELECT * FROM restaurants", conn)
restaurants.head()

result = (
    final_df
    .groupby(["restaurant_id", "restaurant_name_y"])
    .agg(
        avg_order_value=("total_amount", "mean"),
        total_orders=("order_id", "count")
    )
    .reset_index()
    .query("total_orders < 20")
    .sort_values(by="avg_order_value", ascending=False)
    .head(1)
)

result

# Orders + Users
orders_users = pd.merge(
    orders,
    users,
    on="user_id",
    how="left"
)

# Add Restaurant data
final_df = pd.merge(
    orders_users,
    restaurants,
    on="restaurant_id",
    how="left"
)

final_df.head()

final_df.to_csv("final_food_delivery_dataset.csv", index=False)
print("✅ Final dataset created")

files.download("final_food_delivery_dataset.csv")

top_city = (
    final_df[final_df["membership"] == "Gold"]
    .groupby("city")["total_amount"]
    .sum()
    .reset_index()
    .sort_values(by="total_amount", ascending=False)
    .head(1)
)

top_city

top_cuisine = (
    final_df
    .groupby("cuisine")["total_amount"]
    .mean()
    .reset_index()
    .sort_values(by="total_amount", ascending=False)
    .head(1)
)

top_cuisine

high_value_users_count = (
    final_df
    .groupby("user_id")["total_amount"]
    .sum()
    .reset_index()
    .query("total_amount > 1000")
    ["user_id"]
    .nunique()
)

high_value_users_count

top_rating_range = (
    final_df
    .assign(
        rating_range=pd.cut(
            final_df["rating"],
            bins=[0, 2, 3, 4, 5],
            labels=["0–2", "2–3", "3–4", "4–5"]
        )
    )
    .groupby("rating_range")["total_amount"]
    .sum()
    .reset_index()
    .sort_values(by="total_amount", ascending=False)
    .head(1)
)

top_rating_range

top_city_avg = (
    final_df[final_df["membership"] == "Gold"]
    .groupby("city")["total_amount"]
    .mean()
    .reset_index()
    .sort_values(by="total_amount", ascending=False)
    .head(1)
)

top_city_avg

result = (
    final_df
    .groupby("cuisine")
    .agg(
        distinct_restaurants=("restaurant_id", "nunique"),
        total_revenue=("total_amount", "sum")
    )
    .reset_index()
    .sort_values(
        by=["distinct_restaurants", "total_revenue"],
        ascending=[True, False]
    )
    .head(1)
)

result

gold_order_percentage = round(
    (final_df[final_df["membership"] == "Gold"].shape[0] / final_df.shape[0]) * 100
)

gold_order_percentage

(
    final_df
    .groupby("restaurant_name_y")
    .agg(
        avg_order_value=("total_amount", "mean"),
        total_orders=("order_id", "count")
    )
    .reset_index()
    .query("total_orders < 20")
    .sort_values(by="avg_order_value", ascending=False)
    .head(1)
)

top_combination = (
    final_df
    .groupby(["city", "cuisine"])["total_amount"]
    .sum()
    .reset_index()
    .sort_values(by="total_amount", ascending=False)
    .head(1)
)

top_combination

result = (
    final_df
    .groupby(["membership", "cuisine"])["total_amount"]
    .sum()
    .reset_index()
)

# Create combined label
result["combination"] = result["membership"] + " + " + result["cuisine"] + " cuisine"

# Get highest revenue combination
final_answer = result.sort_values(by="total_amount", ascending=False).head(1)

final_answer[["combination", "total_amount"]]

top_quarter = (
    final_df
    .assign(order_date=pd.to_datetime(final_df["order_date"], format="%d-%m-%Y"))
    .assign(quarter=lambda x: x["order_date"].dt.to_period("Q"))
    .groupby("quarter")["total_amount"]
    .sum()
    .reset_index()
    .sort_values(by="total_amount", ascending=False)
    .head(1)
)

top_quarter

(
    final_df
    .groupby("restaurant_name_y")
    .agg(
        avg_order_value=("total_amount", "mean"),
        total_orders=("order_id", "count")
    )
    .reset_index()
    .query("total_orders < 20")
    .sort_values(by="avg_order_value", ascending=False)
    .head(1)
)["restaurant_name_y"]

final_df[final_df["membership"] == "Gold"].shape[0]

round(final_df[final_df["city"] == "Hyderabad"]["total_amount"].sum())

final_df["user_id"].nunique()

round(final_df[final_df["membership"] == "Gold"]["total_amount"].mean(), 2)

final_df[final_df["rating"] >= 4.5].shape[0]

top_city = (
    final_df[final_df["membership"] == "Gold"]
    .groupby("city")["total_amount"]
    .sum()
    .idxmax()
)

final_df[
    (final_df["membership"] == "Gold") &
    (final_df["city"] == top_city)
].shape[0]

final_df.shape[0]